class DlcNames:
    baseGame = None
    leviathans = "Leviathans"
    utopia = "Utopia"
    megacorp = "Megacorp"
    apocalypse = "Apocalypse"
    federations = "Federations"
    nemesis = "Nemesis"
    overlord = "Overlord"
    galacticParagons = "Galactic Paragons"
    astralPlanes = "Astral Planes"
    cosmicStorms = "Cosmic Storms"
    machineAge = "The Machine Age"

    syntheticDawn = "Synthetic Dawn Story Pack"
    distantStars = "Distant Stars Story Pack"
    ancientRelics = "Ancient Relics Story Pack"
    firstContact = "First Contact Story Pack"

    humanoidsSpecies = "Humanoids Species Pack"
    plantoidsSpecies = "Plantoids Species Pack"
    lithoidsSpecies = "Lithoids Species Pack"
    necroidsSpecies = "Necroids Species Pack"
    aquaticsSpecies = "Aquatics Species Pack"
    toxoidsSpecies = "Toxoids Species Pack"