techs = [
    {"name":"reactor", "levels":5, "area":None, "category":None, "tier":1, "non_research": None,
     "progType": None},
    {"name":"hyperdrive", "levels":4, "area":None, "category":None, "tier":1, "non_research": None,
     "progType": None},
    {"name":"thruster", "levels":4, "area":None, "category":None, "tier":1, "non_research": None,
     "progType": None},
    {"name":"ship", "levels":5, "area":None, "category":None, "tier":1, "non_research": None,
     "progType": None},
    {"name":"starbase", "levels":3, "area":None, "category":None, "tier":2, "non_research": None,
     "progType": None},
    {"name":"wormhole", "levels":2, "area":None, "category":None, "tier":3, "non_research": None,
     "progType": None},
    {"name":"corvette_upgrades", "levels":3, "area":None, "category":None, "tier":2, "non_research": None,
     "progType": None},
    {"name":"destroyer_upgrades", "levels":3, "area":None, "category":None, "tier":2, "non_research": None,
     "progType": None},
    {"name":"cruiser_upgrades", "levels":3, "area":None, "category":None, "tier":2, "non_research": None,
     "progType": None},
    {"name":"battleship_upgrades", "levels":3, "area":None, "category":None, "tier":2, "non_research": None,
     "progType": None},
    {"name":"titan_upgrades", "levels":2, "area":None, "category":None, "tier":3, "non_research": None,
     "progType": None},
    {"name":"starbase_upgrades", "levels":2, "area":None, "category":None, "tier":3, "non_research": None,
     "progType": None},
    {"name":"strike_craft", "levels":4, "area":None, "category":None, "tier":1, "non_research": None,
     "progType": None},
    {"name":"orbital_habitats", "levels":3, "area":None, "category":None, "tier":2, "non_research": None,
     "progType": None},
    {"name":"ship_armor", "levels":4, "area":None, "category":None, "tier":1, "non_research": None,
     "progType": None},
    {"name":"armor_hardener", "levels":2, "area":None, "category":None, "tier":3, "non_research": None,
     "progType": None},
    {"name":"robotics", "levels":5, "area":None, "category":None, "tier":1, "non_research": None,
     "progType": None},
    {"name":"space_mining", "levels":5, "area":None, "category":None, "tier":1, "non_research": None,
     "progType": None},
    {"name":"planetary_mining", "levels":3, "area":None, "category":None, "tier":2, "non_research": None,
     "progType": None},
    {"name":"alloy_production", "levels":2, "area":None, "category":None, "tier":3, "non_research": None,
     "progType": None},
    {"name":"consumer_goods", "levels":2, "area":None, "category":None, "tier":3, "non_research": None,
     "progType": None},
    {"name":"afterburners", "levels":2, "area":None, "category":None, "tier":3, "non_research": None,
     "progType": None},
    {"name":"planetary_build_speed", "levels":2, "area":None, "category":None, "tier":3, "non_research": None,
     "progType": None},
    {"name":"housing", "levels":3, "area":None, "category":None, "tier":2, "non_research": None,
     "progType": None},
    {"name":"mass_drivers", "levels":4, "area":None, "category":None, "tier":1, "non_research": None,
     "progType": None},
    {"name":"kinetic_artillery", "levels":2, "area":None, "category":None, "tier":3, "non_research": None,
     "progType": None},
    {"name":"mass_accelerators", "levels":2, "area":None, "category":None, "tier":3, "non_research": None,
     "progType": None},
    {"name":"autocannon", "levels":4, "area":None, "category":None, "tier":1, "non_research": None,
     "progType": None},
    {"name":"flak_battery", "levels":3, "area":None, "category":None, "tier":2, "non_research": None,
     "progType": None},
    {"name":"missiles", "levels":4, "area":None, "category":None, "tier":1, "non_research": None,
     "progType": None},
    {"name":"swarm_missiles", "levels":2, "area":None, "category":None, "tier":3, "non_research": None,
     "progType": None},
    {"name":"torpedoes", "levels":3, "area":None, "category":None, "tier":2, "non_research": None,
     "progType": None},
    {"name":"shields", "levels":5, "area":None, "category":None, "tier":1, "non_research": None,
     "progType": None},
    {"name":"science_lab", "levels":3, "area":None, "category":None, "tier":2, "non_research": None,
     "progType": None},
    {"name":"station_science", "levels":5, "area":None, "category":None, "tier":1, "non_research": None,
     "progType": None},
    {"name":"colony_ship", "levels":2, "area":None, "category":None, "tier":3, "non_research": None,
     "progType": None},
    {"name":"research_ai", "levels":3, "area":None, "category":None, "tier":2, "non_research": None,
     "progType": None},
    {"name":"encryption", "levels":3, "area":None, "category":None, "tier":2, "non_research": None,
     "progType": None},
    {"name":"decryption", "levels":3, "area":None, "category":None, "tier":2, "non_research": None,
     "progType": None},
    {"name":"reactor_booster", "levels":3, "area":None, "category":None, "tier":2, "non_research": None,
     "progType": None},
    {"name":"shield_hardener", "levels":2, "area":None, "category":None, "tier":3, "non_research": None,
     "progType": None},
    {"name":"sensors", "levels":3, "area":None, "category":None, "tier":2, "non_research": None,
     "progType": None},
    {"name":"power_plants", "levels":3, "area":None, "category":None, "tier":2, "non_research": None,
     "progType": None},
    {"name":"lasers", "levels":4, "area":None, "category":None, "tier":1, "non_research": None,
     "progType": None},
    {"name":"lances", "levels":2, "area":None, "category":None, "tier":3, "non_research": None,
     "progType": None},
    {"name":"plasma", "levels":3, "area":None, "category":None, "tier":2, "non_research": None,
     "progType": None},
    {"name":"arc_emitter", "levels":2, "area":None, "category":None, "tier":3, "non_research": None,
     "progType": None},
    {"name":"disruptors", "levels":3, "area":None, "category":None, "tier":2, "non_research": None,
     "progType": None},
    {"name":"energy_torpedoes", "levels":2, "area":None, "category":None, "tier":3, "non_research": None,
     "progType": None},
    {"name":"point_defense", "levels":2, "area":None, "category":None, "tier":3, "non_research": None,
     "progType": None},
    {"name":"trade", "levels":3, "area":None, "category":None, "tier":2, "non_research": None,
     "progType": None},
    {"name":"farming", "levels":4, "area":None, "category":None, "tier":1, "non_research": None,
     "progType": None},
    {"name":"habitability", "levels":4, "area":None, "category":None, "tier":1, "non_research": None,
     "progType": None},
    {"name":"hospital", "levels":2, "area":None, "category":None, "tier":3, "non_research": None,
     "progType": None},
    {"name":"terrain_blockers", "levels":9, "area":None, "category":None, "tier":1, "non_research": None,
     "progType": None},
    {"name":"terraforming", "levels":3, "area":None, "category":None, "tier":2, "non_research": None,
     "progType": None},
    {"name":"leader_genetics", "levels":3, "area":None, "category":None, "tier":2, "non_research": None,
     "progType": None},
    {"name":"gene_tailoring", "levels":6, "area":None, "category":None, "tier":1, "non_research": None,
     "progType": None},
    {"name":"army_genetics", "levels":3, "area":None, "category":None, "tier":2, "non_research": None,
     "progType": None},
    {"name":"transgenesis", "levels":3, "area":None, "category":None, "tier":2, "non_research": None,
     "progType": None},
    {"name":"fleet_size", "levels":5, "area":None, "category":None, "tier":1, "non_research": None,
     "progType": None},
    {"name":"naval_capacity", "levels":4, "area":None, "category":None, "tier":1, "non_research": None,
     "progType": None},
    {"name":"army_defense", "levels":2, "area":None, "category":None, "tier":3, "non_research": None,
     "progType": None},
    {"name":"army_offense", "levels":2, "area":None, "category":None, "tier":3, "non_research": None,
     "progType": None},
    {"name":"psionics", "levels":3, "area":None, "category":None, "tier":2, "non_research": None,
     "progType": None},
    {"name":"starbase_capacity", "levels":2, "area":None, "category":None, "tier":3, "non_research": None,
     "progType": None},
    {"name":"campaigns", "levels":2, "area":None, "category":None, "tier":3, "non_research": None,
     "progType": None},
    {"name":"planet_government", "levels":3, "area":None, "category":None, "tier":2, "non_research": None,
     "progType": None},
    {"name":"planet_infrastructure", "levels":2, "area":None, "category":None, "tier":3, "non_research": None,
     "progType": None},
    {"name":"bureaucracy", "levels":4, "area":None, "category":None, "tier":1, "non_research": None,
     "progType": None},
    {"name":"thralls", "levels":2, "area":None, "category":None, "tier":3, "non_research": None,
     "progType": None},
    {"name":"psionic_shield", "levels":2, "area":None, "category":None, "tier":3, "non_research": None,
     "progType": None},
    {"name":"embassy", "levels":2, "area":None, "category":None, "tier":3, "non_research": None,
     "progType": None},
    {"name":"capital_production", "levels":3, "area":None, "category":None, "tier":2, "non_research": None,
     "progType": None},
    {"name":"psionic_covenants", "levels":4, "area":None, "category":None, "tier":1, "non_research": None,
     "progType": None},
    {"name":"bioreactor", "levels":2, "area":None, "category":None, "tier":3, "non_research": None,
     "progType": None},
]
items = [
    {"type":"tech", "name":"reactor", "description":"Progressive reactor technology"},
    {"type":"tech", "name":"hyperdrive", "description":"Progressive hyperdrive technology"},
    {"type":"tech", "name":"thruster", "description":"Progressive thruster technology"},
    {"type":"tech", "name":"ship", "description":"Progressive ship technology"},
    {"type":"tech", "name":"starbase", "description":"Progressive starbase technology"},
    {"type":"tech", "name":"wormhole", "description":"Progressive wormhole technology"},
    {"type":"tech", "name":"corvette upgrades", "description":"Progressive corvette upgrades technology"},
    {"type":"tech", "name":"destroyer upgrades", "description":"Progressive destroyer upgrades technology"},
    {"type":"tech", "name":"cruiser upgrades", "description":"Progressive cruiser upgrades technology"},
    {"type":"tech", "name":"battleship upgrades", "description":"Progressive battleship upgrades technology"},
    {"type":"tech", "name":"titan upgrades", "description":"Progressive titan upgrades technology"},
    {"type":"tech", "name":"starbase upgrades", "description":"Progressive starbase upgrades technology"},
    {"type":"tech", "name":"strike craft", "description":"Progressive strike craft technology"},
    {"type":"tech", "name":"orbital habitats", "description":"Progressive orbital habitats technology"},
    {"type":"tech", "name":"ship armor", "description":"Progressive ship armor technology"},
    {"type":"tech", "name":"armor hardener", "description":"Progressive armor hardener technology"},
    {"type":"tech", "name":"robotics", "description":"Progressive robotics technology"},
    {"type":"tech", "name":"space mining", "description":"Progressive space mining technology"},
    {"type":"tech", "name":"planetary mining", "description":"Progressive planetary mining technology"},
    {"type":"tech", "name":"alloy production", "description":"Progressive alloy production technology"},
    {"type":"tech", "name":"consumer goods", "description":"Progressive consumer goods technology"},
    {"type":"tech", "name":"afterburners", "description":"Progressive afterburners technology"},
    {"type":"tech", "name":"planetary build speed", "description":"Progressive planetary build speed technology"},
    {"type":"tech", "name":"housing", "description":"Progressive housing technology"},
    {"type":"tech", "name":"mass drivers", "description":"Progressive mass drivers technology"},
    {"type":"tech", "name":"kinetic artillery", "description":"Progressive kinetic artillery technology"},
    {"type":"tech", "name":"mass accelerators", "description":"Progressive mass accelerators technology"},
    {"type":"tech", "name":"autocannon", "description":"Progressive autocannon technology"},
    {"type":"tech", "name":"flak battery", "description":"Progressive flak battery technology"},
    {"type":"tech", "name":"missiles", "description":"Progressive missiles technology"},
    {"type":"tech", "name":"swarm missiles", "description":"Progressive swarm missiles technology"},
    {"type":"tech", "name":"torpedoes", "description":"Progressive torpedoes technology"},
    {"type":"tech", "name":"shields", "description":"Progressive shields technology"},
    {"type":"tech", "name":"science lab", "description":"Progressive science lab technology"},
    {"type":"tech", "name":"station science", "description":"Progressive station science technology"},
    {"type":"tech", "name":"colony ship", "description":"Progressive colony ship technology"},
    {"type":"tech", "name":"research ai", "description":"Progressive research ai technology"},
    {"type":"tech", "name":"encryption", "description":"Progressive encryption technology"},
    {"type":"tech", "name":"decryption", "description":"Progressive decryption technology"},
    {"type":"tech", "name":"reactor booster", "description":"Progressive reactor booster technology"},
    {"type":"tech", "name":"shield hardener", "description":"Progressive shield hardener technology"},
    {"type":"tech", "name":"sensors", "description":"Progressive sensors technology"},
    {"type":"tech", "name":"power plants", "description":"Progressive power plants technology"},
    {"type":"tech", "name":"lasers", "description":"Progressive lasers technology"},
    {"type":"tech", "name":"lances", "description":"Progressive lances technology"},
    {"type":"tech", "name":"plasma", "description":"Progressive plasma technology"},
    {"type":"tech", "name":"arc emitter", "description":"Progressive arc emitter technology"},
    {"type":"tech", "name":"disruptors", "description":"Progressive disruptors technology"},
    {"type":"tech", "name":"energy torpedoes", "description":"Progressive energy torpedoes technology"},
    {"type":"tech", "name":"point defense", "description":"Progressive point defense technology"},
    {"type":"tech", "name":"trade", "description":"Progressive trade technology"},
    {"type":"tech", "name":"farming", "description":"Progressive farming technology"},
    {"type":"tech", "name":"habitability", "description":"Progressive habitability technology"},
    {"type":"tech", "name":"hospital", "description":"Progressive hospital technology"},
    {"type":"tech", "name":"terrain blockers", "description":"Progressive terrain blockers technology"},
    {"type":"tech", "name":"terraforming", "description":"Progressive terraforming technology"},
    {"type":"tech", "name":"leader genetics", "description":"Progressive leader genetics technology"},
    {"type":"tech", "name":"gene tailoring", "description":"Progressive gene tailoring technology"},
    {"type":"tech", "name":"army genetics", "description":"Progressive army genetics technology"},
    {"type":"tech", "name":"transgenesis", "description":"Progressive transgenesis technology"},
    {"type":"tech", "name":"fleet size", "description":"Progressive fleet size technology"},
    {"type":"tech", "name":"naval capacity", "description":"Progressive naval capacity technology"},
    {"type":"tech", "name":"army defense", "description":"Progressive army defense technology"},
    {"type":"tech", "name":"army offense", "description":"Progressive army offense technology"},
    {"type":"tech", "name":"psionics", "description":"Progressive psionics technology"},
    {"type":"tech", "name":"starbase capacity", "description":"Progressive starbase capacity technology"},
    {"type":"tech", "name":"campaigns", "description":"Progressive campaigns technology"},
    {"type":"tech", "name":"planet government", "description":"Progressive planet government technology"},
    {"type":"tech", "name":"planet infrastructure", "description":"Progressive planet infrastructure technology"},
    {"type":"tech", "name":"bureaucracy", "description":"Progressive bureaucracy technology"},
    {"type":"tech", "name":"thralls", "description":"Progressive thralls technology"},
    {"type":"tech", "name":"psionic shield", "description":"Progressive psionic shield technology"},
    {"type":"tech", "name":"embassy", "description":"Progressive embassy technology"},
    {"type":"tech", "name":"capital production", "description":"Progressive capital production technology"},
    {"type":"tech", "name":"psionic covenants", "description":"Progressive psionic covenants technology"},
    {"type":"tech", "name":"bioreactor", "description":"Progressive bioreactor technology"},
]